### ISSUE TITLE
Initial Logging Initiative Release

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1025]
This issue holds unique checklist items for the first logging-initiative release

### Todos 
- [ ] Make sure everything is documented in newrelic.yml 
- [ ] Write release notes ([see this link for the main copy - Internal](https://docs.google.com/document/d/1vC-LZu2_DMNNHnbTfNU0b0nEhIQvtzwMchjUUhUfSHA/edit))
- [ ] Update the logs-in-context documentation with links to our config docs and release notes and the correct release version
- [ ] Update `lib/tasks/config.rake` to have a section for `application_logging`
- [ ] Add config options to documentation
