### ISSUE TITLE
Refactor ActiveRecord::Migration dynamic class naming

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1208]
Starting in Active Record 5.0, migrations are expected to have version strings corresponding with the Rails version they were created with in square brackets at the end of the inheriting `ActiveRecord::Migration` class. Since the Ruby agent covers multiple ActiveRecord versions below and above 5.0, we've addressed this using the following snippet:

```
ActiveRecord::VERSION::STRING >= "5.0.0" ? ActiveRecord::Migration["#{ActiveRecord::VERSION::STRING[0]}.0"] : ActiveRecord::Migration
```

This snippet is used in a few areas of the codebase. Rather than continuing to copy/paste the code, let's rewrite it as a method and call the method instead.

### Tasks
- [ ] Write a test_helper method that includes the above code in its body (this may live in our unit test helper file or may need to live within the multiverse suite, some experimentation required!)
- [ ] Replace the calls to this code with the method 
- [ ] Verify the tests relying on these sample migrations still pass
