### ISSUE TITLE
Ensure that 100% of all unit and integration tests are working locally (not via automated CI)

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1962]
**NOTE: This is a prerequisite task that does not require K2**

We'll be iterating on some combinations of code and configuration parameters that would work best when tested locally without having to have anything pushed up to GitHub to engage with our Actions based CI.

We should make sure our Docker Compose based approach to running all unit and integration tests is working for 100% of tests. We've seen some issue crop up with a couple of the containers (especially the MySQL and Postgres ones) and other miscellaneous hiccups. Let's get the local Docker Compose solution into a reliable, efficient state. 

Suites to fix:

- [x] elasticsearch #1973 : won't fix (Docker error - elasticsearch not needed to test k2)
- [x] memcache #1972 : won't fix (removing support/ test suite)
- [x] redis #1971 won't fix (Docker error - elasticsearch not needed to test k2)
- [x] active_record_pg #1979

**Comment by hannahramadan** [comment]
Redis and Elasticsearch are still failing - both with the same issue of having trouble establishing a connection. Addressing this Docker issue isn't necessary to test K2, especially since these test work properly when run on the CI. Closing this issue.

Notes from Elasticsearch issue:

- An issue with Docker is preventing the Elasticsearch client from establishing a connection, no matter the port.
- Docker is successfully opening the desired ports - a curl request made from the local machine is successful. However, a curl request made from inside a container fails. There may be an issue with containers talking to each other. 
- The same error issue is present in Redis tests,  #1971. However, rabbitmq tests, which also need to open a port, pass.
- We've:
  - compared docker images across Ruby playground and agent yml files.
  - tried new ports, env var (based on playground, yml files, and internet research), allocated additional memory 
  - Looked into Docker updates (not extensively, something could've and probably did change with Docker)
