### ISSUE TITLE
Investigate: Record data collected by Server-Timing Middleware

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#911]
### Rails' Changelog Text 
> Server-Timing specification defines how the server can communicate to browsers performance metrics about the request it is responding to. The ServerTiming middleware is enabled by default on the development environment by default using the config.server_timing setting and set the relevant duration metrics in the Server-Timing header. The full specification for Server-Timing header can be found in: https://www.w3.org/TR/server-timing/#dfn-server-timing-header-field
>  _Sebastian Sogamoso, Guillermo Iguaran_

### Questions
* Can this benefit our agent’s recording abilities?
* Is this within the purview of the Ruby Agent, or is it covered by a different agent? 

### Ideas 
* Add as an attribute on a metric that’s already getting recorded
* Could be behind a feature flag/configuration option that runs only when the setting is enabled within Rails

### Task list:

- [x] Determine which bit of Rails code generates the header. Can we prepend/chain it?
ServerTiming#call [generates the header](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/middleware/server_timing.rb#L58-L74). 
- [x] Do we already have access to the all (not just Rails) browser headers elsewhere in the agent? Maybe we can just look for the presence of this additional header.
We have access to them through `MiddlewareTracing#cal`
- [x] The browser timing header (used by the browser agent) might be a good place to look
No agents, including browser, support `Server-Timing`. This is a current [feature request of the node agent ](https://github.com/newrelic/node-newrelic/issues/1341)
- [x] Maybe in the transaction where we grab headers, that would be a helpful place to hook in for this new header (see `transaction.rb`)
We can grab Sever-Timing through `MiddlewareTracing#call`

**Comment by kaylareopelle** [comment]
Tabling to do more internal research to determine whether this is recorded by another Agent.

**Comment by hannahramadan** [comment]
Notes: 
- [Rails ServerTiming class](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/middleware/server_timing.rb), under ActionDispatch. It was introduced in Rails7.
- This is a current [feature request of the node agent ](https://github.com/newrelic/node-newrelic/issues/1341)
- No mention of `Server-Timing` (or any variant) in the browser agent.
- `server_timing` is [disabled by default](https://github.com/rails/rails/blob/main/railties/lib/rails/application/configuration.rb#L86) in Rails
- The syntax of the Server-Timing header allows for [metrics communications in different ways](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing): server metric name only, metric with value, metric with value and description, and metric with description.

**Comment by hannahramadan** [comment]
Further investigation w/ @kaylareopelle
- We are reporting 3 HTTP response headers: `http.statusCode`, `contentLength`, and `contentType`. These headers are added as transaction attributes in `transaction.rb`, and discovered in `middleware_tracing.rb`. We are not currently set up to report on additional/custom headers, however, we do receive them through as the second item in the `results` array variable when calling `MiddlewareTracing#call`. 
- `Server-Timing` is a header key with a string value. For example:
> "Server-Timing"=> "sql.active_record;dur=13.86, start_processing.action_controller;dur=0.20, instantiation.active_record;dur=21.80, render_partial.action_view;dur=1.77, render_template.action_view;dur=37.60, render_layout.action_view;dur=130.13, process_action.action_controller;dur=174.32"
- 5 of the 7 recorded activities in `Sever-Timing` are already reported by the agent. We have plans to subscribe to an untracked one. 
  - `sql.active_record` - [active_record_notifications.rb#L101-L104](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/active_record_notifications.rb#L101-L104)
  - `start_processing.action_controller` - currently on deck to subscribe to #1510 
  - `instantiation.active_record` - Not tracked by the agent.
  - `render_partial.action_view` - [action_view.rb#L24-L27](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/rails_notifications/action_view.rb#L24-L27)
  - `render_template.action_view` - [action_view.rb#L24-L27](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/rails_notifications/action_view.rb#L24-L27)
  - `render_layout.action_view`- [action_view.rb#L24-L27](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/rails_notifications/action_view.rb#L24-L27)
  - `process_action.action_controller` - [action_controller.rb#L30-L31](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/rails_notifications/action_controller.rb#L30-L31)
 
Because we provide much of the same information as server-timing, I don't see much value in adding. Recording server-timing data would give customers this information as a part of a transaction attribute(s), which in the UI could be of value. It would be nice to know if this, or the ability to track custom/additional headers, is of interest to customers.

**Comment by kaylareopelle** [comment]
Closing this issue as "Won't Do" since we report on most of the content in the header already.

**Comment by kaylareopelle** [comment]
https://github.com/newrelic/newrelic-ruby-agent/issues/911
