### ISSUE TITLE
Add configuration options for logging initiative

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#983]
_Duplicate of [LOGGING-7295: Add new config values to newrelic.yml and other documentation (Internal)](https://newrelic.atlassian.net/browse/LOGGING-7295)_

### Settings created with initial logging PR
| Config value | EAP Default | Set by ENV? | In default_source? | In newrelic.yml? | 
| --- | --- | --- | --- | --- |
| `application_logging.forwarding.enabled` | false | ✅ | ✅  | ❌ | 
| `application_logging.forwarding.max_samples_stored` | **10000*** | ✅ | ✅ | ❌ |

_the max samples stored value in the existing PR is set to 2,000. it should now be 10,000_

All other settings need to be added. 

This issue also comprises the work that is described in: 
* [LOGGING-7302 (Internal)](https://newrelic.atlassian.net/browse/LOGGING-7302) to add an application_logging.metrics.enabled flag by updating the existing `instrumentation.logger` metrics to use this value. Supportability metrics related to Logging should still be recorded. This only influences the metric gathering for Logging/* metrics, not overall instrumentation installation.
* [LOGGING-7293 (Internal)](https://newrelic.atlassian.net/browse/LOGGING-7293) to turn off all application logging features. This should also allow the Supportability metrics related to logging to still be recorded.

### Task Breakdown 
- Add/update configuration options as needed. Use [Configuration section of Engineering Brief: Logging in Agents (Internal)](https://docs.google.com/document/d/1HG9RD0NAYiLtR8ZFfH0obLbVZiVmQxOt3k8xBz-RZaQ/edit#heading=h.tgy5byczdmxa) to verify required settings and defaults for EAP
- Update `newrelic.yml` configuration option template file to include descriptions and default values
- Update docs site config options page with new options, keep in a draft PR status until we’re ready to go GA
- May also have some language-specific documentation coming out about logging logic, but this isn’t the scope here
- Engineering brief / Agent spec has the latest information

This work does not need to include writing documentation for how to use the new features introduced by the logging initiative. That will be covered by the docs team and the Ruby Agent team may be tapped in for assistance.

**Comment by kaylareopelle** [comment]
An alternative way to implement this feature would be to break it out into sub-tasks per configuration option. I decided to leave it as one large item to start and see how the estimates played out.

**Comment by kaylareopelle** [comment]
Todos: 
- [ ] Increase application_logging.forwarding.max_samples_stored to 10000
- [ ] add application_logging.forwarding.max_samples_stored to newrelic.yml
- [ ] turn application_logging.forwarding.enabled to false
- [ ] add application_logging.forwarding.enabled to newrelic.yml
- [ ] add application_logging.metrics.enabled, default true 
- [ ] add application_logging.metrics.enabled, to newrelic.yml

Represented in other tasks: 
* add application_logging.enabled (#978)
* add application_logging.local_decorating.enabled (#998, low EAP priority)

Not required for EAP
* add event_harvest_config.harvest_limits.log_event_data controlled by application_logging.forwarding.max_samples_stored

This will likely be a smaller scope than anticipated. More in the 1-3 range.

**Comment by kaylareopelle** [comment]
Closed by #1003
